name: Build 4.9

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:   
    - name: Setup build kernel environment
      run: |
        echo "BUILD_TIME=$(TZ=Asia/Shanghai date "+%Y%m%d%H%M")" >> $GITHUB_ENV
        sudo apt-get update
        sudo apt-get install git ccache automake flex lzop bison gperf build-essential zip curl zlib1g-dev g++-multilib libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng maven libssl-dev pwgen libswitch-perl policycoreutils minicom libxml-sax-base-perl libxml-simple-perl bc libc6-dev-i386 lib32ncurses5-dev libx11-dev lib32z-dev libgl1-mesa-dev xsltproc unzip device-tree-compiler python2 python3

        git clone --depth 1 https://github.com/LineageOS/android_prebuilts_clang_kernel_linux-x86_clang-r416183b.git clang
        mkdir gcc-64
        wget -O gcc-aarch64.tar.gz https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+archive/refs/tags/android-12.1.0_r27.tar.gz
        tar -C gcc-64/ -zxvf gcc-aarch64.tar.gz
        mkdir gcc-32
        wget -O gcc-arm.tar.gz https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/+archive/refs/tags/android-12.1.0_r27.tar.gz
        tar -C gcc-32/ -zxvf gcc-arm.tar.gz
        mkdir misc
        wget -O misc.tar.gz https://android.googlesource.com/platform/prebuilts/misc/+archive/refs/heads/android-msm-crosshatch-4.9-android12/linux-x86.tar.gz
        tar -C misc/ -zxvf misc.tar.gz
             
    - name: Build kernel
      run: |
        git clone --depth 1 https://github.com/LineageOS/android_kernel_google_msm-4.9 kernel
        cd $GITHUB_WORKSPACE
        cd kernel
        export ARCH=arm64
        export SUBARCH=arm64
        export PATH=$GITHUB_WORKSPACE/gcc-64/bin:$PATH
        export PATH=$GITHUB_WORKSPACE/gcc-32/bin:$PATH
        export PATH=$GITHUB_WORKSPACE/clang/bin:$PATH
        export PATH=$GITHUB_WORKSPACE/misc/lz4:$PATH
        export PATH=$GITHUB_WORKSPACE/misc/dtc:$PATH
        export PATH=$GITHUB_WORKSPACE/misc/libufdt:$PATH
        export LD_LIBRARY_PATH=$GITHUB_WORKSPACE/clang/lib64:$LD_LIBRARY_PATH
        git config --global user.email "bot@example.com"
        git config --global user.name "bot"

        curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -
        make O=out ARCH=arm64 CC=clang AR=llvm-ar NM=llvm-nm OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump READELF=llvm-readelf OBJSIZE=llvm-size STRIP=llvm-strip HOSTCC=clang HOSTCXX=clang++ HOSTLD=ld.lld CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-android- CROSS_COMPILE_ARM32=arm-linux-androideabi- b1c1_defconfig
        make O=out ARCH=arm64 CC=clang AR=llvm-ar NM=llvm-nm OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump READELF=llvm-readelf OBJSIZE=llvm-size STRIP=llvm-strip HOSTCC=clang HOSTCXX=clang++ HOSTLD=ld.lld CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-android- CROSS_COMPILE_ARM32=arm-linux-androideabi-
    
    - name: Upload the zip
      uses: actions/upload-artifact@v4
      with:
        name: 4.9_${{ env.BUILD_TIME}}
        path: |
          kernel/out/arch/arm64/boot/*
